### ISSUE TITLE
[*] Make /checkout always fail regardless of what's in cart or DB

### ISSUE THREAD

**Issue by realkosty** [sentry-demos/empower#251]
A few projects have complex, realistic if-conditions for when to through exception in `/checkout`.
There are two issues with it:
* Outside contributors need to know that you have to add 2 items to the cart for it to crash.
* This creates brittleness - recently someone changed something in React `/products` as a result checkouts started to succeed and stopped generating errors.
* There is no purpose to it. Our demo flow does not require Checkout to succeed ever. The only reason maybe is to have realistic looking code in stack trace code context.. if we want to keep that we can just replace condition with one that's always true ([for example like was done in Flask](https://github.com/sentry-demos/empower/pull/247/files#diff-64c622a07292ca0f1aef670a3685053e1989264d328f66d3a7345d047754442bR104)) or move out the logic to some functions that always return true.

express - :x: [/checkout route](https://github.com/sentry-demos/empower/blob/8e72d70b3405d6a787ac2c273513f4d3f5ce43b8/express/server.js#L209)
ruby-on-rails - :x: [/checkout route](https://github.com/sentry-demos/empower/blob/8e72d70b3405d6a787ac2c273513f4d3f5ce43b8/ruby-on-rails/app/controllers/api/v1/checkout_controller.rb#L90)
spring-boot - :x:[ /checkout route](https://github.com/sentry-demos/empower/blob/8e72d70b3405d6a787ac2c273513f4d3f5ce43b8/spring-boot/src/main/java/com/sentrydemos/springboot/AppController.java#L212), [checkout()](https://github.com/sentry-demos/empower/blob/8e72d70b3405d6a787ac2c273513f4d3f5ce43b8/spring-boot/src/main/java/com/sentrydemos/springboot/AppController.java#L233)

**This issue is blocking** https://github.com/sentry-demos/empower/issues/252

**Comment by cstavitsky** [comment]
@realkosty https://github.com/sentry-demos/empower/pull/265 is ready for review

Note that I didn't test it on Rails 😢 wasted enough time with environment BS (related to openssl and failure to install ruby 2.7.0 -- I tried most of the suggestions). The change is so simple, that I'm hoping we can either just approve on sight and deploy, or that you/someone can quickly test locally.

**Comment by ndmanvar** [comment]
tested rails. works ✅

**Comment by cstavitsky** [comment]
Code changes have been merged in

**Comment by ndmanvar** [comment]
@cstavitsky can we do our final testing and close this one accordingly?
Looking to get the profile use-case in -> https://github.com/sentry-demos/empower/issues/252

**Comment by realkosty** [comment]
Tested this is working
