### ISSUE TITLE
[react] Un-rollback #249 (browser profiling by Jonas)

### ISSUE THREAD

**Issue by realkosty** [sentry-demos/empower#252]
PR/commit to revert: https://github.com/sentry-demos/empower/pull/249

**Depends on:** https://github.com/sentry-demos/empower/issues/251 (don't do this until that issue is resolved)

**Comment by ndmanvar** [comment]
@realkosty - can you pick this one up? let's get this in now that checkouts all fail

**Comment by realkosty** [comment]
@JonasBa this should be good to un-revert if you haven't done so already

**Comment by realkosty** [comment]
https://github.com/sentry-demos/empower/pull/271

**Comment by JonasBa** [comment]
@realkosty @ndmanvar can someone explain what is failing here? Is it the unknown id?

**Comment by realkosty** [comment]
@JonasBa this is not an issue any more - something about your change affected the contents of cart being sent to the backend as a result backend stopped throwing (intentional) error. We decided to stop pretending this is a real application and just made all backends fail regardless of what's in the cart since that is the behavior we want to generate errors used in demo.
