### ISSUE TITLE
[react] Browser profiling - show unminified stack frames in browser profile

### ISSUE THREAD

**Issue by cstavitsky** [sentry-demos/empower#261]
Browser profile currently shows minified frames, which makes the profile not that useful.

First (and most problematically!), functions in our own source code seem minified:

![image (54)](https://github.com/sentry-demos/empower/assets/12092849/39338e57-6b8d-4f25-97d2-12f3bb8446bb)

Also, as I understand was previously communicated over Slack, other frames are minified:

This seems to be related [to minified stack frames](https://testorg-az.sentry.io/issues/4403010073/?project=5808623&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=2) in this error (click ‘full stack trace’):

![Screenshot 2023-08-24 at 1 06 55 PM](https://github.com/sentry-demos/empower/assets/12092849/a52c2da7-292e-4abc-bc14-41ba791de740)

Goal is to show a slowdown on /products transaction profile, and we aren’t able to effectively do that as SEs with the minified code called

- [Example profile](https://testorg-az.sentry.io/profiling/profile/frontend-javascript/3bb7f27ca35a4ef198c95fd4b2b3bf04/flamegraph/?colorCoding=by+system+vs+application+frame&query=&sorting=call+order&tid=0&view=top+down)

![Screenshot 2023-08-24 at 1 09 48 PM](https://github.com/sentry-demos/empower/assets/12092849/b095e9d5-60e0-4b2b-8d88-1a4b3517c423)

Need to:
- Determine whether these frames *should* be unminified. Per Jonas B in an internal conversation-- chrome devtools also shows a profile with minified react functions so it doesn't seem like a problem isolated to our dashboard
- If those particular frames 'should not' be unminified, then maybe we can manipulate the profile to add additional function calls within our source code, making the majority of frames legible to those watching a demonstration

**Comment by ndmanvar** [comment]
@JonasBa - should the function `E` be sourcemapped? as `Products.js` is sourcemapped but function name is doesn't seem like it is
cc @cstavitsky

**Comment by JonasBa** [comment]
@ndmanvar what is that function doing? If it is Products.js calling into some react internal function, then it probably will not be deobfuscated (as neither of the other react frames are deobfuscated)

**Comment by ndmanvar** [comment]
> Jonas Badalic
> Yeah, and I see create react app sets the right sourcemap option + includes the sourcemap loader so package sourcemaps should be included. This seems like it is react specific

**Comment by ndmanvar** [comment]
> Jonas
> I think I found the issue -> react builds currently do not expose sourcemaps https://github.com/facebook/react/pull/26446
[#26446 Generate sourcemaps for production build artifacts](https://github.com/facebook/react/pull/26446)

**Comment by realkosty** [comment]
@ndmanvar @JonasBa this is where my investigation on this ended (you probably got further than that but just in case):
https://sentry.slack.com/archives/C05FA9D2PDM/p1691104329763509?thread_ts=1690226802.724409&cid=C05FA9D2PDM

**Comment by cstavitsky** [comment]
@JonasBa in your view, does [your workaround we merged](https://github.com/sentry-demos/empower/pull/287) fully address this ticket and we can close it out? If not, what still remains?

**Comment by JonasBa** [comment]
@cstavitsky the large majority of functions should now appear as unmodified, but there are likely still parts that might be unminified. This will slowly get better as we add more sourcemaps to the react-prod-sourcemaps plugin. I would close this issue and create new ones for the frames we find that are still minified

**Comment by cstavitsky** [comment]
>  I would close this issue and create new ones for the frames we find that are still minified

Sounds good, closing. I will create a new issue for new ones that are still minified
