### ISSUE TITLE
Create a span that causes frontend-only performance slowdown

### ISSUE THREAD

**Issue by cstavitsky** [sentry-demos/empower#273]
### Current state

In the current demo, we show a slow React transaction whose root cause is directly tied to a slow endpoint that we then trace to a backend service.

- [/products transaction summary](https://demo.sentry.io/performance/summary/?project=5808623&query=transaction.op%3Apageload&referrer=performance-transaction-summary&statsPeriod=30d&transaction=%2Fproducts&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29)
- [Example event](https://demo.sentry.io/performance/frontend-javascript:b172523540fd42d0bb3c53b96a0ac51d/?project=5808623&query=transaction.op%3Apageload&referrer=performance-transaction-summary&showTransactions=recent&statsPeriod=30d&transaction=%2Fproducts&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29)

![Screenshot 2023-09-14 at 1 44 38 PM](https://github.com/sentry-demos/empower/assets/12092849/82fada5b-3501-4e2a-bcd5-a5b004bc3c15)
![Screenshot 2023-09-14 at 1 42 31 PM](https://github.com/sentry-demos/empower/assets/12092849/7ef8c0cd-3997-4e96-a0fc-535c69238add)

This is a strong narrative for customers who are interested in Sentry on the frontend and backend, but doesn’t land as well when speaking with teams of only frontend developers.

### Goal state 

Add a frontend-only slowdown. This new slowdown must:

1. Occur in the frontend-only – not be dependent on performance problems from another downstream service
2. ~Take between 3 and 5 seconds~ (we found this is not possible)
3. ~Jeopardizes/compromises LCP (We want to be able to demonstrate to customers how Sentry surfaces a problem impacting LCP, then permits it to be solved)~ (we are deprioritizing this and making it a separate ticket; the most important thing is that there **is** a frontend-only slowdown that will resonate with a developer, the web vitals are not a critical part of this)
4. Have a specific story/problem associated with it, as well as an indication how a given developer could solve it, based on the insights provided by Sentry. Please make it clear internally what the user would do to solve the slowdown, so that SEs can incorporate this into the demo flow.

##### Ideas/options of how to accomplish goal state

- The easiest way may be to leverage the [render bottleneck introduced by Jonas](https://github.com/sentry-demos/empower/blob/e1865f4ff068e8f81064ad194945b74393705210/react/src/components/Products.js#L69-L71) for profiling purposes – for example, wrapping the slow-rendering ProductCards in a custom span. Something like the following (may require slowing down the render bottleneck slightly more to hit 3 seconds):

![Screenshot 2023-09-14 at 2 52 44 PM](https://github.com/sentry-demos/empower/assets/12092849/d6590e44-ef6a-41bc-8bea-1919fc071aaf)

- Or, you may come up with any other slowdown story you like, as long as it meets the requirements, can be explained to a prospect during a demo, and is sufficiently instrumented with enough spans to tell a story

**Comment by cstavitsky** [comment]
@cstavitsky todo: (We'll need two different flows -- slowdown in the existing performance products transaction, then a frontend-only slowdown possibly in a different transaction)

**Comment by HazAT** [comment]
How about creating a `<SlowListComponent />` which just shows 5(?) entries but what it does, it iterates over 10k entries and just uses those last 5 entries?
And when iterating over the entries always trigger a redraw `setState`

Probably quick enough to not fully disturb the frontend experience but enough to be measurable.

**Comment by ndmanvar** [comment]
I think that might work @HazAT  (:

@cstavitsky - what do you think? we can have the other slowdowns in a different transaction (e.g. uncompressed-assets/etc.) but this gets us "a react slowdown" in our products transaction
and from there we can go to the backen (via HTTP span) or drill down on the FE slowness.
i.e. kind of like we do for our backend demo..
i.e. there was also this frontend slowness in addition to the slow HTTP request/response, let's debug that..(kind of like we do for get_iterator) in the backend [which is the second slowdown outside of the n+1 db queries)

**Comment by cstavitsky** [comment]
Whoops - did not realize you'd unassigned, Francesco, removed you. I will be ensuring your work gets stitched together in the full frontend-only flow and don't anticipate more work needed on this ticket at this time

**Comment by cstavitsky** [comment]
Updated requirements to put this span behind the frontend-only feature flag and changing status to 'blocked' until I do that ticket.
