### ISSUE TITLE
Upgrade backend SDKs for Query Insights data

### ISSUE THREAD

**Issue by cstavitsky** [sentry-demos/empower#281]
Pretty sure we need to upgrade SDKs in order for Query Insights to look decent.

- [Recommended SDK versions](https://docs.sentry.io/product/performance/query-insights/#recommended-sdk-versions)

## Current status

Query description is blank on the Query Insights page no matter which filters are applied. Probably this is due to outdated SDK version.

![Screenshot 2023-09-27 at 10 58 01 AM](https://github.com/sentry-demos/empower/assets/12092849/81f436db-5561-4862-9e46-0405a888b429)

**Comment by ndmanvar** [comment]
@cstavitsky looks like we have to select the project
![image](https://github.com/sentry-demos/empower/assets/314061/9c2c57e7-af22-4466-b45b-43f240375878)

**Comment by cstavitsky** [comment]
@ndmanvar nice! closing this
