### ISSUE TITLE
Instrument Flask service with DDM 

### ISSUE THREAD

**Issue by serglom21** [sentry-demos/empower#339]
We should keep track of the following metrics in the flask service:

1. Latency of DB request to fetch Products ([line of code](https://github.com/sentry-demos/empower/blob/master/flask/src/main.py#L146)) -> Distribution
2. Latency of get_iterator method ([line of code](https://github.com/sentry-demos/empower/blob/master/flask/src/main.py#L153))-> Distribution
3. Number of Failed Checkouts ([line of code)](https://github.com/sentry-demos/empower/blob/master/flask/src/main.py#L117)-> Counter

**Comment by ndmanvar** [comment]
Also please add any other metrics you see fit.
Looking to get our app 'outfitted' with (relevant) metrics

**Comment by serglom21** [comment]
Completed on [355](https://github.com/sentry-demos/empower/pull/355)
